Controllers/KrajController.cs
using FotoDB.ILogic;
using FotoDB.Logic;
using FotoDB.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace FotoDB.Controllers
{
    public class KrajController : Controller
    {
        private readonly IKrajManager _krajManager;

        public KrajController(IKrajManager krajManager)
        {
            _krajManager = krajManager;
        }
        //public IActionResult Index(string sortOrder, string currentFilter, string searchString, int? page)
        //public async Task<IActionResult> Index(string sortOrder, string searchString)
        //public IActionResult Index(string sortOrder, string searchString)
        //public IActionResult Index(
        //                            string sortOrder,
        //                            string currentFilter,
        //                            string searchString,
        //                            int? pageNumber)
        public IActionResult Index(
                                    string sortOrder,
                                    string searchString)
        {
            //var manager = new KrajManager();

            ////ręczne dodawanie danych do modelu i do bazy
            //var kraj = new KrajModel();
            //kraj.KrajModelID = 1;
            //kraj.Nazwa = "Polska";
            //manager.AddKraj(kraj);

            ////ręczne usuwanie danych z modelu i z bazy
            //manager.RemoveKraj(5);

            ////ręczne update danych w modelu i w bazie
            //var kraj = new KrajModel();
            //kraj.KrajModelID = 2;
            //kraj.Nazwa = "Niemcy";
            //manager.UpdateKraj(kraj);

            ////ręczna zmiana danych w modelu i w bazie
            //manager.ChangeNazwa(3, "Szkocja");

            //var krajs = manager.GetKrajs();

            //var krajs = _krajManager.GetKrajs();
            //return View(krajs);

            //ViewBag.CurrentSort = sortOrder;
            //ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            //ViewBag.IDSortParm = sortOrder == "ID" ? "id_desc" : "ID";

            //if (searchString != null)
            //{
            //    page = 1;
            //}
            //else
            //{
            //    searchString = currentFilter;
            //}

            //ViewBag.CurrentFilter = searchString;

            ViewData["CurrentSort"] = sortOrder;
            ViewData["NazwaSortParm"] = String.IsNullOrEmpty(sortOrder) ? "nazwa_desc" : "";
            ViewData["IDSortParm"] = sortOrder == "id" ? "id_desc" : "id";

            //if (searchString != null)
            //{
            //    pageNumber = 1;
            //}
            //else
            //{
            //    searchString = currentFilter;
            //}

            ViewData["CurrentFilter"] = searchString;


            var krajs = from k in _krajManager.GetKrajs()
                        select k;


            if (!String.IsNullOrEmpty(searchString))
            {
                krajs = krajs.Where(k => k.Nazwa.ToLower().Contains(searchString.ToLower()));
            }

            switch (sortOrder)
            {
                case "nazwa_desc":
                    krajs = krajs.OrderByDescending(k => k.Nazwa);
                    break;
                case "id":
                    krajs = krajs.OrderBy(k => k.KrajModelID);
                    break;
                case "id_desc":
                    krajs = krajs.OrderByDescending(k => k.KrajModelID);
                    break;
                default:
                    krajs = krajs.OrderBy(k => k.Nazwa);
                    break;
            }
            //int pageSize = 5;
            //int pageNumber = (page ?? 1);
            //return View(krajs.ToPagedList(pageNumber, pageSize));
            //return View(await krajs.AsNoTracking().ToListAsync());
            //return View(krajs);
            //int pageSize = 3;
            //return View(PaginatedList<KrajModel>.CreateAsync(krajs.AsQueryable(), pageNumber ?? 1, pageSize));
            return View(krajs);
        }

        

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(KrajModel kraj)
        {
            //var manager = new KrajManager();
            //manager.AddKraj(kraj);
            _krajManager.AddKraj(kraj);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            //var manager = new KrajManager();
            //var kraj = manager.GetKraj(id);
            var kraj = _krajManager.GetKraj(id);
            return View(kraj);
        }

        [HttpPost]
        public IActionResult DeleteConfirm(int id)
        {
            //var manager = new KrajManager();
            try
            {
                //manager.RemoveKraj(id);
                _krajManager.RemoveKraj(id);
                return RedirectToAction("Index");
            }
            catch (Exception)
            {
                ViewBag.ErrorTitle = "Delete";
                ViewBag.ErrorMessage = "You cannot delete this record because it does not exist in the database.";
                return View("Error");
            }   
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            //var manager = new KrajManager();
            //var kraj = manager.GetKraj(id);
            var kraj = _krajManager.GetKraj(id);
            return View(kraj);
        }
        
        [HttpPost]
        public IActionResult Edit(KrajModel kraj)
        {
            //var manager = new KrajManager();
            //manager.UpdateKraj(kraj);
            _krajManager.UpdateKraj(kraj);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            //var manager = new KrajManager();
            //var kraj = manager.GetKraj(id);
            var kraj = _krajManager.GetKraj(id);
            return View(kraj);
        }


        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Kraj/Create.cshtml
@model FotoDB.Models.KrajModel

@{
    ViewData["Title"] = "Dodaj kraj";
}

<h1>Dodaj kraj</h1>

<h4>Utwórz nowy kraj w bazie danych</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nazwa" class="control-label"></label>
                <input asp-for="Nazwa" class="form-control" placeholder="Podaj nazwę kraju"/>
                <span asp-validation-for="Nazwa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Dodaj" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index" class="btn btn-info">Powrót do listy krajów</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Kraj/Delete.cshtml
@model FotoDB.Models.KrajModel

@{
    ViewData["Title"] = "Usuń kraj";
}

<h1>Usuń kraj</h1>

<h3>Czy na pewno chcesz usunąć ten kraj z bazy danych?</h3>
<div>
    <h4>KrajModel</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.KrajModelID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.KrajModelID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nazwa)
        </dd>
    </dl>
    
    <form asp-action="DeleteConfirm" asp-route-id="@Model.KrajModelID">
        <input type="hidden" asp-for="KrajModelID" />
        <input type="submit" value="Usuń" class="btn btn-danger" />
        <a asp-action="Details" asp-route-id="@Model.KrajModelID" class="btn btn-info">Powrót do szczegółów</a>
        <a asp-action="Index" class="btn btn-info">Powrót do listy krajów</a>
    </form>
</div>

Views/Kraj/Details.cshtml
@model FotoDB.Models.KrajModel

@{
    ViewData["Title"] = "Szczegóły kraju: " + ViewData.Model.Nazwa;
}

<h1>Szczegóły kraju: @Html.DisplayFor(model => model.Nazwa)</h1>

<div>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.KrajModelID)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.KrajModelID)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nazwa)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nazwa)
        </dd>
    </dl>
</div>
<div class="btn-group" role="group" aria-label="Basic example">
    <a asp-action="Edit" asp-route-id="@Model.KrajModelID" class="btn btn-primary">Edytuj</a>
    <a asp-action="Delete" asp-route-id="@Model.KrajModelID" class="btn btn-danger">Usuń</a>
    <a asp-action="Index" class="btn btn-info">Powrót do listy krajów</a>
</div>

Views/Kraj/Edit.cshtml
@model FotoDB.Models.KrajModel

@{
    ViewData["Title"] = "Edytujesz kraj: " + ViewData.Model.Nazwa;
}

<h1>Edytujesz kraj: @Html.DisplayFor(model => model.Nazwa)</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="KrajModelID" />
            <div class="form-group">
                <label asp-for="Nazwa" class="control-label"></label>
                <input asp-for="Nazwa" class="form-control" placeholder="Podaj nazwę kraju"/>
                <span asp-validation-for="Nazwa" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Zapisz" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details" asp-route-id="@Model.KrajModelID" class="btn btn-info">Powrót do szczegółów</a>
    <a asp-action="Index" class="btn btn-info">Powrót do listy krajów</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Kraj/Index.cshtml
@model IEnumerable<FotoDB.Models.KrajModel>
@*@model PagedList.IPagedList<FotoDB.Models.KrajModel>
    @using PagedList.Mvc;
    @using PagedList;
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />*@
@*@model PaginatedList<FotoDB.Models.KrajModel>*@

@{
    ViewData["Title"] = "Kraje";
}

<h1>Kraje</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Dodaj nowy</a>
</p>

@*@using (Html.BeginForm("Index", "Kraj", FormMethod.Get))
{
    <div>
        Wyszukaj po nazwie: @Html.TextBox("SearchString", ViewBag.CurrentFilter as string)
        <input type="submit" value="Wyszukaj" />
    </div>
}*@
<hr />
<form asp-action="Index" method="get">
    <div class="form-actions no-color">
        <div class="form-group">
            <input type="text" class="form-control" name="SearchString" placeholder="Podaj nazwę kraju" value="@ViewData["CurrentFilter"]"/>
            <input type="submit" value="Wyszukaj" class="btn btn-primary" />
            <a asp-action="Index" class="btn btn-info">Powrót do listy krajów</a>
        </div>
    </div>
</form>
<hr />
<table class="table table-dark table-hover table-bordered">
    <thead>
        <tr>
            <th>

                @*@Html.ActionLink(@Html.DisplayNameFor(model => model.KrajModelID), "Index", new { sortOrder = ViewBag.IDSortParm })*@
                @*<a asp-action="Index" asp-route-sortOrder="@ViewData["IDSortParm"]">@Html.DisplayNameFor(model => model.KrajModelID)</a>*@
                @*@Html.ActionLink("KrajModelID", "Index", new { sortOrder = ViewBag.IDSortParm, currentFilter = ViewBag.CurrentFilter })*@
                <a asp-action="Index" asp-route-sortOrder="@ViewData["IDSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">@Html.DisplayNameFor(model => model.KrajModelID)</a>

            </th>
            <th>
                @*@Html.ActionLink(@Html.DisplayNameFor(model => model.Nazwa), "Index", new { sortOrder = ViewBag.NameSortParm })*@
                @*<a asp-action="Index" asp-route-sortOrder="@ViewData["NameSortParm"]">@Html.DisplayNameFor(model => model.Nazwa)</a>*@
                @*@Html.ActionLink("Nazwa", "Index", new { sortOrder = ViewBag.NameSortParm, currentFilter = ViewBag.CurrentFilter })*@
                <a asp-action="Index" asp-route-sortOrder="@ViewData["NazwaSortParm"]" asp-route-currentFilter="@ViewData["CurrentFilter"]">@Html.DisplayNameFor(model => model.Nazwa)</a>
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.KrajModelID)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nazwa)
                </td>
                <td>
                    <a asp-action="Details" asp-route-id="@item.KrajModelID" class="btn btn-outline-info">Pokaż szczegóły</a>
                </td>
            </tr>
        }
    </tbody>
</table>
@*<br />
    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

    @Html.PagedListPager(Model, page => Url.Action("Index",
        new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))*@


@*@{
    var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
    var nextDisabled = !Model.HasNextPage ? "disabled" : "";
}*@

@*<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex - 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @prevDisabled">
    Previous
</a>
<a asp-action="Index"
   asp-route-sortOrder="@ViewData["CurrentSort"]"
   asp-route-pageNumber="@(Model.PageIndex + 1)"
   asp-route-currentFilter="@ViewData["CurrentFilter"]"
   class="btn btn-default @nextDisabled">
    Next
</a>*@